// draw_text_border(x,y,text);
var c = draw_get_color();
draw_set_color(c_black);
draw_text(argument0-1,argument1-1,argument2);
draw_text(argument0-1,argument1,argument2);
draw_text(argument0-1,argument1+1,argument2);
draw_text(argument0,argument1-1,argument2);
draw_text(argument0,argument1+1,argument2);
draw_text(argument0+1,argument1-1,argument2);
draw_text(argument0+1,argument1,argument2);
draw_text(argument0+1,argument1+1,argument2);
draw_set_color(c);
draw_text(argument0,argument1,argument2);
